version: "3.8"

services:
  backend:
    build: .  
    container_name: springboot_app
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
    networks:
      - springboot_network
    depends_on:
      - mongodb

  frontend:
    build: ./Frontend/hasan 
    container_name: angular_app
    ports:
      - "4200:80" 
    depends_on:
      - backend
    networks:
      - springboot_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - springboot_network
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    networks:
      - springboot_network
    depends_on:
      - mongodb
    restart: unless-stopped

networks:
  springboot_network:
    driver: bridge

volumes:
  mongo_data:
