services:
  # Spring Boot service
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile.springboot
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://testuser:eqmzmbwkaM6pi9Wu@cluster0.wvqeulj.mongodb.net/baylanka?retryWrites=true&w=majority&appName=Cluster0
      - GEMINI_API_KEY:AIzaSyAW2RJ9jreYV4CThrS57nERwHz8ZhPAHdM
    networks:
      - backend-network

  # Angular service
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.angular
    container_name: angular-app
    ports:
      - "80:80"
    networks:
      - frontend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
